version: '3.7'
services:
  db:
   image: ewalsh200/janus_cass
   environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_CGROUP_MEMORY_LIMIT=true"
      - "DEBUG=true"
   volumes:
      - ./data:/opt/elassandra-6.2.3.21/data
   cap_add:
      - IPC_LOCK
   ulimits:
      memlock: -1
   networks:
     iwordnet:
       ipv4_address: 172.29.0.2
  kibana:
    image: kibana:6.8.12
    environment:
      - "ELASTICSEARCH_URL=http://172.29.0.2:9200"
    ports:
      - "5601:5601"
    networks:
      iwordnet:
        ipv4_address: 172.29.0.100
  spark:
    image: ewalsh200/toyspark
    volumes:
      - ./spark:/code
    ports:
      - "8080:8080"
    networks:
      iwordnet:
        ipv4_address: 172.29.0.4
  slave:
    image: ewalsh200/toyspark-slave
    networks:
      iwordnet:
        ipv4_address: 172.29.0.101
  zeppelin:
    image: ewalsh200/zeppelin
    ports:
      - "8087:8087"
    volumes:
      - ./logs:/opt/zeppelin-0.9.0-preview1-bin-all/logs
      - ./notebook:/opt/zeppelin-0.9.0-preview1-bin-all/notebook
      - ./zconf:/opt/zeppelin-0.9.0-preview1-bin-all/conf
    environment:
      - "ZEPPELIN_ADDR=172.29.0.6"
      - "ZEPPELIN_PORT=8087"
    networks:
      iwordnet:
        ipv4_address: 172.29.0.6


networks:
  iwordnet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24
